spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lwz7254591
    url: jdbc:mysql://localhost:3306/ky_graduate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
  servlet:
    multipart:
      # 设置最大文件上传限制
      max-file-size: 10MB
tencent:
  cos:
    file:
      bucketName: ky2fe-1316858065
      regionName: ap-chengdu
      cosHost: https://ky2fe-1316858065.cos.ap-chengdu.myqcloud.com
deviceOption:
  isOpenDevice: false

pictureUploadOption:
  # 改变图片存储方式，COS 方式为上传到腾讯 COS 存储，LOCAL 方式为本地字节流流方式存储到数据库
  faceImgStoreMode: COS

requestUrl:
  # 基础
  baseUrl: http://192.168.31.155:8090
  # 设备管理
  device:
    getDeviceKey: /getDeviceKey
    setPassWord: /setPassWord
  # 人员管理
  person:
    # 人员注册
    createPerson: /person/create
    # 人员更新
    updatePerson: /person/update
    # 人员删除
    deletePerson: /person/delete
    # 设置人员进入许可时间
    personPassTime: /person/createPasstime
  face:
    # 人员人脸注册
    createFace: /face
    # 人脸删除
    deleteFace: /face/delete
    # 人员人脸清空
    clearFace: /face/deletePerson
server:
  port: 8089